; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:generic_f072rb]
platform = ststm32
board = generic_stm32f072rbt6
;board = nucleo_f072rb
framework = arduino
board_build.mcu = stm32f072rbt6
board_build.f_cpu = 48000000L
upload_protocol = dfu
lib_archive = no
build_flags = 
    -I include
    -Werror
    -Wall
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
monitor_dtr = 1
monitor_port = COM19
monitor_speed = 115200