[platformio]
default_envs = openmppt
boards_dir = boards

# --- Global Environment Settings ---
[env]
monitor_speed = 115200
monitor_dtr = 1
build_flags = 
	-Werror
	-Wall

# --- openMPPT v1.1 Custom Hardware ---
[env:openmppt]
platform = ststm32
board = openmppt
framework = stm32cube
board_build.mcu = stm32f072rbt6
board_build.f_cpu = 48000000L
lib_deps = STLinkedResources

# Build Automation (CubeMX Integration)
extra_scripts = pre:scripts/setup_cubemx_env_auto.py
platform_packages = toolchain-gccarmnoneeabi@1.120301.0

# Upload Configuration (DFU)
upload_protocol = dfu
;upload_protocol = blackmagic
;upload_port = /dev/ttyACM2

# --- Native Testing Environment ---
[env:native]
platform = native
build_flags = 
	${env.build_flags}
	-D NATIVE_TEST 
	-I Core/Inc 
	-I test/test_mppt
build_src_filter = +<Core/Src/mppt.c> -<Core/Src/main.c>
lib_ignore = 
	STLinkedResources
	STM32_USB_Device_Library-CDC
	STM32_USB_Device_Library-Core
